name = "gimp"
icon = "assets/logo.png"
title = "GIMP"
intro = "强大的开源图像编辑软件"
category = "creating"
screenshot = ["assets/gimp.jpg"]
banner = "assets/gimp-banner.png"

[package_flags]
unoffical = false
verified = true
non_native = false
windows_app = false
telemetry = false
service_limited = false

[package_info]
publisher = "GIMP Team"
source = "https://www.gimp.org/"
version = "2.10.38"
inner_version = 21038
update_date = "2024-07-10"
install_size = 250000000
homepage = "https://www.gimp.org/"
