name = "minecraft"
icon = "assets/logo.png"
title = "Minecraft"
intro = "沙盒建造与冒险游戏"
category = "games"
screenshot = ["assets/minecraft.jpg"]
banner = "assets/minecraft-banner.png"

[package_flags]
unoffical = false
verified = true
non_native = false
windows_app = false
telemetry = true
service_limited = false

[package_info]
publisher = "Mojang Studios"
source = "https://www.minecraft.net/"
version = "1.20.1"
inner_version = 1
update_date = "2024-07-10"
install_size = 500000000
homepage = "https://www.minecraft.net/"