[[packages]]
name = "firefox"
intro = "Mozilla Firefox 網頁瀏覽器"
icon = "assets/logo.png"

[[packages]]
name = "steam"
intro = "Steam 遊戲平台"
icon = "assets/logo.png"

[[packages]]
name = "vlc"
intro = "VLC 媒體播放器"
icon = "assets/logo.png"

[[packages]]
name = "wechat"
intro = "即时通讯工具"
icon = "assets/logo.png"
