[[packages]]
name = "firefox"
intro = "Mozilla Firefox 網頁瀏覽器"
icon = "assets/firefox.png"

[[packages]]
name = "steam"
intro = "Steam 遊戲平台"
icon = "assets/steam.png"

[[packages]]
name = "vlc"
intro = "VLC 媒體播放器"
icon = "assets/vlc.png"
